FROM 759105516845.dkr.ecr.ap-northeast-1.amazonaws.com/stg-madworld-market-base:node-14 as builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM 759105516845.dkr.ecr.ap-northeast-1.amazonaws.com/stg-madworld-market-base:node-14-slim
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3000

CMD ["npm", "run", "start:prod"]
