export const SERVER_DOMAIN = process.env.NEXT_PUBLIC_SERVER_DOMAIN;
export const SERVER_API_ENDPOINT = process.env.NEXT_PUBLIC_SERVER_API_ENDPOINT;
export const AWS_API_ENDPOINT = process.env.NEXT_PUBLIC_AWS_API_ENDPOINT;
export const AWS_CLOUDFRONT_ENDPOINT = process.env.NEXT_PUBLIC_AWS_CLOUDFRONT_API_ENDPOINT;

export const NETWORK_CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID;
export const NETWORK_RPC_URL = process.env.NEXT_PUBLIC_RPC_URL;
export const NETWORK_INFURA_KEY = process.env.NEXT_PUBLIC_INFURA_API_KEY;
export const NETWORK_ID = process.env.NEXT_PUBLIC_NETWORK_ID;

export const METAMASK_DEEP_LINK = process.env.NEXT_PUBLIC_METAMASK_DEEPLINK;
export const LINK_SCAN = process.env.NEXT_PUBLIC_LINK_SCAN;
export const AWS_CLOUDFRONT_API_ENDPOINT = process.env.NEXT_PUBLIC_AWS_CLOUDFRONT_API_ENDPOINT;

export const NETWORK_NAME = process.env.NEXT_PUBLIC_NETWORK_NAME;

export const IPFS_SERVER_ENDPOINT = process.env.NEXT_PUBLIC_IPFS_SERVER_ENDPOINT;
export const DEEP_LINK_METAMASK = process.env.NEXT_PUBLIC_DEEP_LINK_METAMASK;
