const LOGIN_LOADING = 'LOGIN/LOGIN_LOADING';
const LOGIN_SUCCESS = 'LOGIN/LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN/LOGIN_FAILURE';

const CLICK_BTN_CREATE = 'LOGIN/CLICK_BTN_CREATE';
const SIGN_WITH_CREATE = 'LOGIN/SIGN_WITH_CREATE';

const OPEN_LOADING_CONNECT = 'LOGIN/OPEN_LOADING_CONNECT';
const CLOSE_LOADING_CONNET = 'LOGIN/CLOSE_LOADING_CONNET';

const GET_UNLOCK_STATUS = 'LOGIN/GET_UNLOCK_STATUS';
const SET_CONNECT_WALLET = 'LOGIN/SET_CONNECT_WALLET';
const SET_CONNECT_NETWORK = 'LOGIN/SET_CONNECT_NETWORK';
const SET_ACCOUNT = 'LOGIN/SET_ACCOUNT';
const SET_WALLET_NAME = 'LOGIN/SET_WALLET_NAME';

export const loginApiActions = {
  LOGIN_LOADING,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  CLICK_BTN_CREATE,
  SIGN_WITH_CREATE,
  OPEN_LOADING_CONNECT,
  CLOSE_LOADING_CONNET,
  GET_UNLOCK_STATUS,
  SET_CONNECT_WALLET,
  SET_ACCOUNT,
  SET_CONNECT_NETWORK,
  SET_WALLET_NAME,
};
