/**
 * * prefix: `${name of reducer}/actions_key`
 */

const MODAL_TOGGLE_MODAL = 'MODAL/TOGGLE_MODAL';
const SET_CONNECT_WALLET_STEP = 'MODAL/SET_CONNECT_WALLET_STEP';
const CLOSE_ALL_MODAL = 'MODAL/CLOSE_ALL_MODAL';

/**
 * * Key of enum must be unique
 */
export enum MODAL_TYPE {
  CONNECT_WALLET = 'CONNECT_WALLET',
  MAKE_AN_OFFER = 'MAKE_AN_OFFER',
  SELL_ASSET = 'SELL_ASSET',
  COMPLETE_CHECKOUT = 'COMPLETE_CHECKOUT',
  ACCEPT_OFFER = 'ACCEPT_OFFER',
  SUCCESS_ITEM_SALE = 'SUCCESS_ITEM_SALE',
  PROCESSING_MAKE_OFFER = 'PROCESSING_MAKE_OFFER',
}

export enum CONNECT_WALLET_STEP_LOGIN {
  SELECT_WALLET = 'SELECT_WALLET',
  WELCOME_BACK = 'WELCOME_BACK',
  ACCOUNT_NOT_EXIST = 'ACCOUNT_NOT_EXIST',
  WRONG_NETWORK = 'WRONG_NETWORK',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  VERIFY_ADDRESS = 'VERIFY_ADDRESS',
  WEB3_NOT_DETECTED = 'WEB3_NOT_DETECTED',
}

export const modalActions = {
  MODAL_TOGGLE_MODAL,
  SET_CONNECT_WALLET_STEP,
  CLOSE_ALL_MODAL,
};
