const GET_SYSTEM_CONFIG_SUCCESS = 'GET_SYSTEM_CONFIG_SUCCESS';
const UPDATE_NATIVE_COIN_USD_PRICE = 'UPDATE_NATIVE_COIN_USD_PRICE';
const UPDATE_UMAD_USD_PRICE = 'UPDATE_UMAD_USD_PRICE';
const UPDATE_UMAD_USD_PRICE_24H_CHANGE = 'UPDATE_UMAD_USD_PRICE_24H_CHANGE';

export const systemActions = {
  GET_SYSTEM_CONFIG_SUCCESS,
  UPDATE_NATIVE_COIN_USD_PRICE,
  UPDATE_UMAD_USD_PRICE,
  UPDATE_UMAD_USD_PRICE_24H_CHANGE,
};
