const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

const USER_UPDATE_BALANCE = 'USER_UPDATE_BALANCE';

const USER_LOGOUT_WALLET = 'USER_LOGOUT_WALLET';

export const userActions = {
  USER_GET_PROFILE_SUCCESS,
  USER_LOGIN_SUCCESS,
  USER_UPDATE_BALANCE,
  USER_LOGOUT_WALLET,
};
