const SET_DUTCH_AUCTION_PRICE = 'SET_DUTCH_AUCTION_PRICE';
const REMOVE_EVENT_CHANGE_PAGE = 'REMOVE_EVENT_CHANGE_PAGE';

export const utilsActions = {
  SET_DUTCH_AUCTION_PRICE,
  REMOVE_EVENT_CHANGE_PAGE,
};
